### PR TITLE
Update setup.bash

### PR DESCRIPTION
**Pull request by davevs**
added dependecies for vanilla linux installes

### CODE REVIEW

**Comment by grendel513** [comment]
Thanks @davevs!  @devGregA can you please take a look to see if this is inline with the install process?

**Comment by devGregA** [comment]
Summoning @cneill :D. I went through all the new libs. Couldn't find major vulnerabilities or issues. Doesn't brake the install for most common systems. @cneill will you weigh in?

**Comment by devGregA** [comment]
Hey @davevs is there a specific OS you're trying to cover? I'm wondering if I can make the list a little lighter by targeting different libs to satisfy the requirements.

**Comment by davevs** [comment]
@devGregA not really. In my view this tool might be tried by not the most tech-savy of people. Following that logic that kind of people probably uses something like mint or ubuntu. I wanted to make sure that the default installer would at least work on those systems to prevent people from abandoning it within a couple of minutes.

**Comment by devGregA** [comment]
Hi @davevs, I've been looking through these packages for a while, and I haven't found a use case for adding these. Most people that we've spoken to are using Ubuntu. These packages aren't required for Dojo to run on Ubuntu and add overhead. If I've missed something please feel free to point it out to me.

**Comment by davevs** [comment]
@devGregA I got errors when using the installer on Mint and had to install these packages manually to make the installer complete. Especially git is necessary to complete the last part of the install, but is not necessarily on the system. Other examples are libtiff and libjpg which are necessary to complete the install.

**Comment by devGregA** [comment]
@davevs gotcha. I'm swamped until Wednesday but will re-examine Mint later in the week.

**Comment by devGregA** [comment]
@davevs sorry for the delay. I haven't forgotten about this.

**Comment by davevs** [comment]
@devGregA np, take your time :)

**Pull request closed without merging**
