### PR TITLE
changed xml to defusedxml

### PR DESCRIPTION
**Pull request by devGregA**
would someone please test with a sample file?

### CODE REVIEW

**Comment by devGregA** [comment]
@cneill or @grendel513 ^

**Comment by grendel513** [comment]
Hey Greg - the code looks great, however defusedxml needs to be installed via pip, which means the setup.py and other files need to be updated as well.  Off the top of my head the files needed are setup.bash, Ansible stuff, and setup.py.

**Comment by devGregA** [comment]
oh jeez, great catch @grendel513 will do.

**Comment by grendel513** [comment]
Hey @devGregA any progress on this?  I know you have been really busy, just checking in.

**Comment by devGregA** [comment]
working on it meow.

**Comment by devGregA** [comment]
Additionally added django-overextends to setup.py

**Comment by grendel513** [comment]
hey @devGregA I didn't think overextends was a dependency...still don't see defusedxml in setup.py or the ansible files.

**Comment by devGregA** [comment]
Should be good to go. I did the final test with a clean ubuntu install, and didn't run into any setup errors. I did hit an SSH problem with vagrant, but I don't think it is related to the current changes. Would someone please verify that the parsers are okay with a dumby upload? I would if I had a spare xml report laying around to test with.

**Comment by devGregA** [comment]
@grendel513 ^ FYI since I don't want to bug you via text to let you know it's ready to review.

**Comment by grendel513** [comment]
Looks good, tested with sample Nexpose report.  Thanks @devGregA

**Pull request merged**
