### PR TITLE
Finding images

### PR DESCRIPTION
**Pull request by grendel513**
Takes care of #63 - @cneill & @devGregA please take a look.  Upgrade documentation found in docs/features.rst under Finding.

### CODE REVIEW

**Comment by devGregA** [comment]
@grendel513 awesome! will review shorlty

**Comment by grendel513** [comment]
@devGregA, @cneill - hold off a bit, i am making some improvements.  I did not like exposing the media root to allow the report async process to have access to them.  give me a day or so.

**Comment by grendel513** [comment]
@devGregA, @cneill all done and ready to be merged once you review it.  i ended up coding a one time token solution for reports (PDF) to be able to access the finding images without having to "authenticate" - once image is rendered once the token is deleted and no linger usable. The token is generated when the image tag is rendered - tied to the finding and size needed.

**Comment by devGregA** [comment]
@grendel513 great work! Merging. I'm correcting my issues with deduplication tonight.

**Pull request merged**
